# docker-compose.yml (en la raíz del proyecto)
version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    # Opcional: healthcheck para Docker Compose
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3